### ISSUE TITLE
Composer require not working due to missing commit hash

### ISSUE THREAD

**Issue by djbfmeel** [endroid/qr-code-bundle#1]
```
  [RuntimeException]                                                           
  Failed to execute git checkout '1e19de01318b4c56daf344194010a0c8bcaf778f' -  
  - && git reset --hard '1e19de01318b4c56daf344194010a0c8bcaf778f' --          
  fatal: reference is not a tree: 1e19de01318b4c56daf344194010a0c8bcaf778f  
```

**Comment by djbfmeel** [comment]
Are you moving this bundle? / wen are you tagging this?

**Comment by endroid** [comment]
Hi @djbfmeel the bundle had been abandoned for quite a while (since QrCode v2.x it resides in the endroid/qrcode library). For QrCode v3.x I'm moving it back to a separate repository. The 3.x versions will be tagged as soon as I think they are stable.

**Comment by djbfmeel** [comment]
Ok thanks!

**Comment by endroid** [comment]
Update: I saw the tags of the old bundle were still present in packagist, so I removed the old tags to make sure composer will not look for non-existent versions.

**Comment by djbfmeel** [comment]
Great!

**Comment by perice** [comment]
Hi @endroid,

so it's not possible to continue using this bundle with Symfony < 3.3?

**Comment by endroid** [comment]
Hi @perice I think the bundle in 2.x is compatible with Symfony < 3.3. You could try that.

**Comment by perice** [comment]
Hey @endroid,

I made it work with my ancient Symfony 2.7.

If you're using an older version of this bundle (version <3.0) and you want to keep using it, you have to:

1) composer.json - change "endroid/qrcode-bundle" to "endroid/qrcode": "~2.0" (this version worked for me)
2) AppKernel.php - change "new Endroid\Bundle\QrCodeBundle\EndroidQrCodeBundle()" to "new Endroid\QrCode\Bundle\QrCodeBundle\EndroidQrCodeBundle()"

I'm only using the "qrcode_data_uri" Twig function, so you may have to change something else.

Thanks for this great bundle!

**Comment by endroid** [comment]
Good to hear the 2.x branch works for you and thank you for leaving a comment. Hope it also helps others!
