### ISSUE TITLE
PHP version dependency

### ISSUE THREAD

**Issue by diriy** [endroid/qr-code-bundle#10]
I tried to install the bundle with composer but it failed. I use PHP 7.1. The error message was the following:

> [InvalidArgumentException]
  Package endroid/qr-code-bundle at version  has a PHP requirement incompatible with your PHP version (5.5.9)

Is there a way to use the bundle with PHP 7.1?

**Comment by endroid** [comment]
Hi @diriy what version is it trying to install? The latest version (3.x) is specifically set up for PHP 7.1 and Symfony 3.4 / 4.0.

**Comment by diriy** [comment]
@endroid, I did just as you mentioned at the documentation.

**Comment by endroid** [comment]
Looks like composer is trying to install an old version. What happens when you explicitly set the version to the latest available?

**Comment by jeroendeleeuw** [comment]
That worked for me by explicitly defining the latest version: `composer require endroid/qr-code-bundle:3.1.2`. Thank you, however I now get the following error:

> PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Rule.php on line 76

> Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Rule.php on line 76

> Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.

The memory_limit was already set to -1, to you know another option for increasing memory size during install? I also killed the Symphony server just to be sure, but it made no difference.

**Comment by endroid** [comment]
@jeroendeleeuw I'm not sure. Did you try the following?

php -d memory_limit=-1 composer.phar ...
