### ISSUE TITLE
can not generate multiple QrCodes at the same time

### ISSUE THREAD

**Issue by makai2016** [endroid/qr-code-bundle#11]
$qrCode = $qrCodeFactory->create();
for ($i = 1; $i <= 10; $i++) {
    $text = uniqid();
    $qrCode->setText($text);
    $qrCode->writeFile(...);
}

The generated QR code is the same

**Comment by endroid** [comment]
Hi @makai2016 thank you for noticing. This should be fixed in 3.2.6.
