### ISSUE TITLE
Incompatibility with Symfony 3.3

### ISSUE THREAD

**Issue by temp** [endroid/qr-code-bundle#12]
The service.yaml uses the !tagged syntax, but this was introduced with Symfony 3.4.
In out Symfony 3.3 app the bundle was updated to 3.1.3, and failed afterwards.
I guess you should raise the minimum version to 3.4. But I can't say which Symfony Component is relevant for this...

**Comment by endroid** [comment]
Hi @temp you're right, this syntax requires DI 3.4 so I updated the requirement. Thank you!

**Comment by temp** [comment]
Hmm but this is a problem. Release 3.1.3 is still there, with invalid dependencies.
Is it possible to Re-release 3.1.3? Or completely remove it? Don't know if composer/packagist supports this somehow...
We will have to add 3.1.3 as conflicted, but this somehow sucks ;-)

**Comment by temp** [comment]
Guess you should've released 3.1.4 with the old behaviour, for everybody using symfony < 3.4, and 3.2.0 with the new behaviour and the changed dependency.
Nevertheless, we added 3.1.3 to the conflicting packages, and we get 3.1.2, so works for us.

**Comment by endroid** [comment]
Yes I understand what you mean but unfortunately the requirement was not detected at that time and it is bad practice in general to rewrite history or remove tags so I think for now you better set your requirement to a previous working version. I'm creating a better test suite so more conflicts like this will be detected earlier but unfortunately this can occur.
