### ISSUE TITLE
Support for symfony 2.8

### ISSUE THREAD

**Issue by creatiombe** [endroid/qr-code-bundle#15]
Hey there, i use symfony 2.8 LTS, the orders mails stopped working after i upgraded all my packages.  I noticed the support for 2.8 was dropped in favor for what?

Can this be fixed?

**Comment by endroid** [comment]
Hi @creatiombe this library indeed does not support Symfony 2.8 because it makes use of more recent framework features. However, the bundle you find bundled in the endroid/qr-code library at version 2.x should still work for older Symfony versions so you could give that a try.
