### ISSUE TITLE
Generate via factory (question)

### ISSUE THREAD

**Issue by Telous** [endroid/qr-code-bundle#18]
Hi,

i'm try to use the 'Generate via factory', but i have a question: how is exactly this works?
 i need create a service to use this? if this is so, what are the parameters to use?

$qrCode = $qrCodeFactory->create('QR Code', ['size' => 200]);

**$qrCodeFactory**, where this variable points?

On use:
"symfony/symfony": "3.4.*",
"endroid/qr-code-bundle": "^3.2",

**Comment by kolyadin** [comment]
I'm interested too

**Comment by endroid** [comment]
Hi @Telous when you install the latest version of the bundle it automatically registers the factory as a service which you can use in any other service. Just use the QrCodeFactory type hint inside your controller (or another service) and autowiring (or explicit wiring via a service definition) makes sure you get an instance to work with.

Please note in the latest version of the bundle the factory is marked private, which means you can not retrieve it from the service container via $container->get(..) but you have to explicitly inject it.
