### ISSUE TITLE
Missing HOW to configure the plugin in the doc

### ISSUE THREAD

**Issue by labgua** [endroid/qr-code-bundle#22]
Perfect integration, I congratulate you!
But a simple thing .... why not write in the documentation HOW to configure it?
The files in .install/symfony/config must simply copy and paste in the config dir for a quick run in project!

I lost half an hour to understand why the twig environment doesn't found the  `qr_code_generate` function.

**Comment by endroid** [comment]
Hi @labgua thank you. The library should automatically install itself via endroid/installer, including the files in the directory you mentioned so I guess something went wrong.

What version of Symfony are you using and what version of the library did you install? Please provide the versions from composer.lock for endroid/qr-code, endroid/qr-code-bundle and endroid/installer and describe the steps / commands you ran to install the library.

**Comment by metalmini** [comment]
The installer does not work as intended, after composer requiring it says:

```
Some files may have been created or updated to configure your new packages.
Please review, edit and commit them: these files are yours.
```
But the config files are not moved to the correct location.

**Comment by endroid** [comment]
Hi @metalmini that message is from Flex so it is not related to my installer. Do you see any other output? If no files were copied, it should probably output something like "Endroid Installer did not detect a compatible project type for auto-configuration".

**Comment by metalmini** [comment]
Nope nothing else

**Comment by endroid** [comment]
That's strange. What version of the qr-code library and the endroid/installer library were installed according to your composer.lock?

**Comment by metalmini** [comment]
` "name": "endroid/installer",
            "version": "1.0.8",`
`            "name": "endroid/qr-code",
            "version": "3.5.4",`

**Comment by endroid** [comment]
@metalmini Looks correct, strange but I can imagine there could be some edge cases or different behavior in different environments so I added a reference to the installation directory to the installation section of the readme. Thank you for your input.
