### ISSUE TITLE
Beginning of URL changed for some scanners

### ISSUE THREAD

**Issue by PaddyLock** [endroid/qr-code-bundle#25]
Hello, I am able to generate the QR codes correctly and they work on QR code scanner Apps, and on the IOS camera built in QR scanner. However on some handheld scanners they seem to add additional characters at the beginning of the scanned QR code URL. 
The beginning of the resulting url is converted from `https://` to `000026https//`
I have checked the code where I am creating the url and I am not changing the string here, as indeed it works fine on other QR scanners resulting in the correct url. The scanner is a Metrologic.

**Comment by endroid** [comment]
Hi @PaddyLock I do not have the scanner you mentioned so I am not able to reproduce or fix this issue given the description but if other scanners (and the built in validator) give the correct string I don't think something is wrong with the QR code. Maybe you could try varying the error correction level or size to see if results are different and send the problematic QR code image to Metrologic. If it appears to be problem in the QR code itself, please let me know, then I will look into it.
