### ISSUE TITLE
Unable to install dev dependency bundle test

### ISSUE THREAD

**Issue by qdequippe** [endroid/qr-code-bundle#27]
Hi,

I would like to contribute to this bundle but when I run `composer install` on the bundle I have this error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for endroid/bundle-test dev-master -> satisfiable by endroid/bundle-test[dev-master].
    - endroid/bundle-test dev-master requires endroid/test dev-master -> satisfiable by endroid/test[dev-master] but these conflict with your requirements or minimum-stability.
```

Any idea how to install it?

**Comment by endroid** [comment]
Hi @qdequippe the bundle-test has been replaced recently. I updated the dependencies, but I still have to make some changes to make it work with the generic test lib. In other words, you have no running test suite at the moment? What do you want to contribute? If it is a small change I can do the testing on my side for now. If it's a bigger change it's good to discuss before you start and maybe wait for the test suite to be ready again.

**Comment by qdequippe** [comment]
Hi @endroid thanks for your reply. I would like to make a small contribution, I would like just to improve the Twig extension using the latest Symfony features (for example using `RuntimeInterface`). Maybe for this I will need to upgrade Twig version so it could be a bigger change for the bundle.

**Comment by qdequippe** [comment]
@endroid do you think it's a big change? I can do it without test suite

**Comment by endroid** [comment]
Hi @qdequippe it is still a bit vague. What is the exact goal of your change / what are the issues you are facing at the moment? You can always just create a pull request and I will look at it. If I think it is useful for the bundle I will merge it.

**Comment by qdequippe** [comment]
@endroid done #28

**Comment by endroid** [comment]
Thank you @qdequippe nice contribution! I have merged it to master, only have to test it before I tag it :)

**Comment by qdequippe** [comment]
thank you @endroid it's just a small contribution 😀
