### ISSUE TITLE
Generate jpg Images?

### ISSUE THREAD

**Issue by resper** [endroid/qr-code-bundle#32]
Hello,
I am using this extension to generate QR Codes, which I use with dompdf. But dompdf works faster with jpg images. How can I generate jpg QR Codes?

**Comment by endroid** [comment]
Hi @resper a JPG writer is not included but you can create one yourself. You can simply copy or extend the PNG writer you find in the endroid/qr-code library and convert the resulting image to JPG.instead.

**Comment by resper** [comment]
Can I just make a fork, edit it and install my version with the composer? I am not so familiar with symfony and bundles.

**Comment by endroid** [comment]
You can also just create the writer class. But if you want to create a fork that is also possible: just push the fork button and add a "repositories" section in your project's composer.json so it loads the resources from your forked package. Like this.

``` json
"repositories": [
        {
            "type": "vcs",
            "url": "url-to-your-fork"
        }
    ]
```

Best practice is to create a specific branch containing your changes and change the require statement to "endroid/qr-code-bundle": "dev-branchname".

Hope this helps. You can also check the composer documentation.
https://getcomposer.org/doc/05-repositories.md#vcs
