### ISSUE TITLE
Symfony 4.3+ deprecation

### ISSUE THREAD

**Issue by skmedix** [endroid/qr-code-bundle#33]
The _if statement_ for `getRootNode()` was correct before https://github.com/endroid/qr-code-bundle/commit/a2911e45192f7597d7367d9d557caf2aa24ccddc. Since that change Symfony throws deprecation notes, as current logic always uses deprecated func instead of new one. It's not a problem for 5.0, as func `root()` is removed there, but 4.4 is LTS and it's pretty annoying. Thanks.

---

```
The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "endroid_qr_code" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.
```

![image](https://user-images.githubusercontent.com/3246162/70396619-02134080-1a0b-11ea-9b3d-3c834a9e6946.png)

**Comment by endroid** [comment]
Hi @skmedix thank you. This should be fixed in 3.4.1.
