### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by fun2life** [endroid/qr-code-bundle#35]
Can you tell me what php libraries the bundle depends on or how else to solve this error?
When I run the script locally it all works fine, but on my server I get the following error when I try to generate a QR code via Twig, both in prod and dev mode:

The option "/qr-code/https:/MYDOMAIN/meinequittung?hash" does not exist. Defined options are: "background_color", "encoding", "error_correction_level", "foreground_color", "label", "label_alignment", "label_font_path", "label_font_size", "label_margin", "logo_height", "logo_path", "logo_width", "margin", "round_block_size", "size", "validate_result", "writer", "writer_options".

If I copy the image path and run it locally, I get the QR Code.

Thanks

**Comment by endroid** [comment]
Hi @fun2life this looks like something in your web server configuration. Apparently the "/qr-code/https:/MYDOMAIN/meinequittung?hash" part is seen as a query string parameter so I think the path of your URL is converted to a query string parameter somehow. The QR code library or bundle itself does not perform any environment-specific handling or change the Request object but an incorrect server configuration can.

Good luck finding the solution, hope this helps ;)

**Comment by fun2life** [comment]
in case someone encounters the same problem when using Twig and qr_code_url()
`<img src="{{ qr_code_url(url('home', {'hash': qrhash}), {size:130, margin:0}) }}" />`

workaround that should do:
`<img src="{{ qr_code_data_uri(url('home', {'hash': qrhash}), {size:130, margin:0}) }}">`
