### ISSUE TITLE
The logo appears above the qrcode and partially hides it

### ISSUE THREAD

**Issue by kstefanini** [endroid/qr-code-bundle#37]
Hi!

And thanks for this sweat bundle.
I'm trying to add a logo inside the generated qrcode using last bundle version, but the logo is covering the qrcode and so I am unable to scan it.

Here is a sample:
![test](https://user-images.githubusercontent.com/5382753/96602454-522d8580-12f3-11eb-8dd1-e6e20cf2c90f.png)

(Generated with default bundle routing : `https://127.0.0.1:8000/qr-code/hifolks.png?size=500&logo_height=150&logo_width=150&logo_path=https://i.picsum.photos/id/258/536/354.jpg?hmac=FJZvafgClrsfFxn1Ce6YeBIo2958pGQCb4jCbEc3SRA`)

Am I missing something, or is this normal behavior?

Thanks!

**Comment by kstefanini** [comment]
I can read [here](https://github.com/endroid/qr-code/issues/216) it's normal to have a logo covering qrcode. 
Is there a possibility to define an empty space (with logo size, width and height) for the logo ?
I can't use logo feature as my logo doesn't display well when tinier than a square.

**Comment by endroid** [comment]
Hi @kstefanini thank you for your question. I don't exactly know what you mean by "empty space" but I can tell that the current implementation only allows for an image overlay that is centered and has a certain width and height. No further logo-specific options than the path, width and height are currently available. Does that answer your question?
