### ISSUE TITLE
Suggestion: Symfony contrib recipe

### ISSUE THREAD

**Issue by factorin-j** [endroid/qr-code-bundle#40]
Maybe we can make use of Symfony Flex contrib recipes instead of using `endroid/installer`?
refs: https://github.com/symfony/recipes-contrib

**Comment by endroid** [comment]
Hi @factorin-j I do like Flex and configuration was originally via Flex but new versions and changes in configuration took too much time via merge requests and configuration was not always in sync with my repository version or was blocking changes on my side so at some point I chose a solution where my configuration lives with my code and is always up to date without any delaying factors which works a lot better for me.
