### ISSUE TITLE
PHP 8.0.x: Unable to generate image: check your GD installation

### ISSUE THREAD

**Issue by fun2life** [endroid/qr-code-bundle#41]
After upgrading to PHP 8 and PHP 8.0.1 respectively, all my Servers (XAMPP and rented comercial space) throw the error

Unable to generate image: check your GD installation

wenn using the following code, or when passing custom parameters
`<img src="{{ qr_code_data_uri('02:af31007d151d4c568442f90d6d129ced#31f0677ea8cba7224341f313d8fda1d2121e5122#') }}">`

The exact same code works fine in PHP versions earlier than 8.0

I'm on Symfony 5.2.1 and have updated all extensions

**Comment by endroid** [comment]
Hi @fun2life the library is not compatible with PHP 8 yet because of a dependency which is not compatible. However you can work around this issue as described in https://github.com/endroid/qr-code/issues/292. Good luck!
