### ISSUE TITLE
Integrate the bundle in symfony 3.2

### ISSUE THREAD

**Issue by joseadame** [endroid/qr-code-bundle#5]
Hi! I don't have Symfony Flex. I tried to put in my appKernel.php the following line:

new Endroid\QrCodeBundle\EndroidQrCodeBundle(),

but I have some errors:

`PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: A "tags" entry must be an array for service "Endroid\QrCodeBundle\Controller\" in services.yaml. Check your YAML syntax. in C:\Users\JoseAdame\Documents\QuadBuild\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Loader\YamlFileLoader.php:270
`
Could you help me?

thanks.

**Comment by linaori** [comment]
You'll have to use 3.3+ for this bundle to work. You should update to 3.3 and then to 3.4 when you have a chance, because 3.2 maintenance is already ended.
