### ISSUE TITLE
Add qr-code to existing FPDF

### ISSUE THREAD

**Issue by laurentmuller** [endroid/qr-code-bundle#51]
It will be nice if we can add a qr-code to an existing PPDF document. Maybe with an function like this:

```PHP
public function addToFpdf(FPDF &$fpdf, float $x, float $y) {
   ...
}
```

**Comment by endroid** [comment]
Hi @laurentmuller thank you for your suggestion. I would like to keep the library and the writer interface as much FPDF agnostic as possible (as in: it the writer should ideally be replaceable with a different PDF library than FPDF). But if it can be done with not too many changes and the document can be passed via the $options array of the write method I am open to this feature.

**Comment by laurentmuller** [comment]
I have created a [pull request](https://github.com/endroid/qr-code/pull/344) within this enhancement.

**Comment by endroid** [comment]
Merged, thank you!
