### ISSUE TITLE
Suggestion: Inform users to enable GD in PHP.

### ISSUE THREAD

**Issue by tonybob-tl** [endroid/qr-code-bundle#54]
Great bundle/tool.

Many PHP environments may not have GD enabled (production environments for sure). It would be good to inform users in Installation or configuration instructions to make sure GD is enabled (via phpinfo() or similar). 
Also, mention it is probably the cause of the "Unable to generate image: check your GD installation" error. Familiarity with GD extension to PHP is required to understand the error. Otherwise, trips to qr-code/issues/308 and 292 is the most likely way users will figure out what's going on.

**Comment by endroid** [comment]
Thank you @tlarsonlgdor. I made the exception more descriptive and added an extra note to the installation instructions in the readme for those who use the library to generate images.
