### ISSUE TITLE
Drop support for PHP 7.3?

### ISSUE THREAD

**Issue by stephanvierkant** [endroid/qr-code-bundle#55]
I see this library still supports PHP 7.3, which is End of Life (EOL) as of today. What's the policy about PHP support? The only [supported versions](https://www.php.net/supported-versions.php) are 7.4, 8.0 and 8.1.

In my opinion libraries should drop support of PHP versions that are end of life, because it makes contributing to this library much easier.

**Comment by endroid** [comment]
See https://github.com/endroid/qr-code-bundle/blob/master/composer.json. The change had already been made ;) Thanks anyway, I totally agree.
