### ISSUE TITLE
Changeable content

### ISSUE THREAD

**Issue by Researcher33** [endroid/qr-code-bundle#57]
Hi, How can we update the information we added to the qr code without changing the qr code. The program will generate a qr code. The content will be changed without changing the qr code. How can i do ?

**Comment by endroid** [comment]
Hi @Researcher33 the QR code is an encoded representation of its contents so the contents and the QR code are inextricably connected. In other words: if you change the QR code you change the contents and if you change the contents you change the QR code.

**Comment by Researcher33** [comment]
Then look this site. Me-qr.com You can change the content.

**Comment by endroid** [comment]
Hi @Researcher33 the service you refer to puts a URL like https://me-qr.com/6942696 in your QR code and me-qr can change what that URL returns but the URL and QR code remain the same because given a QR code its contents can not change.
