### ISSUE TITLE
Required parameter $referenceType follows optional parameter $options in QrCodeRuntime.php on line 40

### ISSUE THREAD

**Issue by fmonts** [endroid/qr-code-bundle#58]
> Deprecated: Required parameter $referenceType follows optional parameter $options in \vendor\endroid\qr-code-bundle\src\Twig\QrCodeRuntime.php on line 40

Can this issue be fixed in qr-code-bundle 3.x?

I cannot update to 4 because I'm using [scheb/2fa-qr-code](https://packagist.org/packages/scheb/2fa-qr-code) that requires endroid/qr-code 3.x...

**Comment by fmonts** [comment]
It's already fixed in 3.x-dev (https://github.com/endroid/qr-code-bundle/commit/abc481ea27d65d18c00ec01852869205b9512611 ), a tag to a stable version would be much appreciated, so we can use it in php8

**Comment by endroid** [comment]
Hi @fmonts I will not create new tags in that branch simply because there are still people that rely on a stable ^3.x version and I cannot guarantee stability with new changes. However, you can still make use the 3.x branch and resolve the issue by using a Composer alias.

```
"require": {
    "endroid/qr-code-bundle": "3.x-dev as 3.0",
}
```

Good luck!
