### ISSUE TITLE
PHP 8.1 deprecation notice in Twig/QrCodeExtension.php

### ISSUE THREAD

**Issue by alexgit2k** [endroid/qr-code-bundle#62]
With PHP 8.1 I am getting the following deprecation notice:
`Method "Twig\Extension\ExtensionInterface::getFunctions()" might add "array" as a native return type declaration in the future. Do the same in implementation "Endroid\QrCodeBundle\Twig\QrCodeExtension" now to avoid errors or add an explicit @return annotation to suppress this message.
`

**Comment by endroid** [comment]
See https://github.com/endroid/qr-code-bundle/issues/60
