### ISSUE TITLE
Symfony 6 (Class Not Found Exception): Attempted to load class "Builder" from namespace "Endroid\QrCode\Builder"

### ISSUE THREAD

**Issue by ok-ttc** [endroid/qr-code-bundle#64]
Hello,

After the update to Symfony 6, I receive this error:

`Attempted to load class "Builder" from namespace "Endroid\QrCode\Builder".
Did you forget a "use" statement for "PhpParser\Builder"?`

I am using Twig to display QR Codes. Like so:

```
{% set share_text = ib.BusinessPage.BusinessName %}

<img src="{{ qr_code_url(url) }}" />
```

I am truly no expert and am learning. Does anyone have an idea what might be causing this?

Thank you for your guidance in this.

**Comment by tobearlabs** [comment]
Check if your config is really updated:
https://github.com/endroid/qr-code-bundle/tree/master/.install/symfony/config/packages
Then the error should be gone.
