### ISSUE TITLE
Do not regenerate `endroid_qr_code.yaml`

### ISSUE THREAD

**Issue by ThomasLandauer** [endroid/qr-code-bundle#65]
I just converted my `endroid_qr_code.yaml` to `endroid_qr_code.php`, but I keep getting the YAML file automatically regenerated. I didn't investigate yet when this happens exactly (`composer update`?), wanted to ask you first:
Since you don't want to drop YAML anytime soon (see https://github.com/endroid/qr-code-bundle/issues/36#issuecomment-1267118736), would it be possible to stop (re)generating the default YAML file if a PHP (or XML?) config file is present?

**Comment by endroid** [comment]
Hi @ThomasLandauer indeed it looks like the behavior changed. I have this on my todo list. For now you should be able to disable auto configuration by completely disabling it or by excluding the specific package.

```
"extra": {
    "endroid": {
        "installer": {
            "enabled": false,
            "exclude": [
                "endroid/qr-code-bundle"
            ]
        }
    }
}
```

**Comment by ThomasLandauer** [comment]
Do you think it's worth mentioning this in README?

**Comment by endroid** [comment]
No it's an issue in a different library.
