### ISSUE TITLE
Suggestion: Support configuration with Symfony Config Builder

### ISSUE THREAD

**Issue by ThomasLandauer** [endroid/qr-code-bundle#67]
See https://symfony.com/blog/new-in-symfony-5-3-config-builder-classes, so that `config/packages/endroid_qr_code.php` looks something like:

```php
<?php declare(strict_types=1);

use Symfony\Config\EndroidQrCodeConfig;

return static function (EndroidQrCodeConfig $endroidQrCodeConfig): void {
    $endroidQrCodeConfig->...
};
```

**Comment by spackmat** [comment]
Yes please, that would be nice.

Edit: I realized that there is no Flex recipe, but endroid/installer is used. So it would be great to change the default config to PHP format, so the installer does not create two `endroid_qr_code.yaml` files on every `composer update`, when PHP-configs are used. ;)

In the meantime, one can disable the installer by adding that config to the extra-section of the project's composer.json:

````
    "extra": {
        "endroid": {
            "installer": {
                "exclude": [
                    "endroid/qr-code-bundle"
                ]
            }
        }
    }
````

**Comment by endroid** [comment]
I created an issue for the installer issue. It should only install once. Thank you. The bundle will continue using yaml for now. PHP config support might be added later.

**Comment by ThomasLandauer** [comment]
What I suggested is obsolete meanwhile, since Symfony dropped it: https://symfony.com/blog/new-in-symfony-7-4-better-php-configuration
