### ISSUE TITLE
Version 5.0.1 not installable with symfony 6.3

### ISSUE THREAD

**Issue by Chris53897** [endroid/qr-code-bundle#74]
Can this `^5.4||^6.4||^7.0` be changed to `^5.4||^6.3||^7.0` to make migration easier for users?

5.0.1 is not installable not installable with symfony 6.3

**Comment by endroid** [comment]
Hi @Chris53897 there are no changes in that version other than the added support for Symfony 7.0 so you won't miss anything :) You can continue to use 5.0.0 and Symfony 6.4 will be released soon.

**Comment by mathieudz** [comment]
Chiming in: it is a bit annoying that composer reports an outdated package after `composer update` because a package manager was a bit too eager.

**Comment by ThomasLandauer** [comment]
See https://github.com/endroid/qr-code-bundle/pull/76 for some background discussion on version support.
