### ISSUE TITLE
Composer download fail.

### ISSUE THREAD

**Issue by SpencerPlanton** [endroid/qr-code-bundle#79]
Hi,
Composer fails with:

Failed to download endroid/quality from source: git was not found in your PATH, skipping source download.

**Comment by endroid** [comment]
Hi @RigidCollision looks like git can not be found, do you have it installed? I see some other people have the same problems with Composer here: https://stackoverflow.com/questions/74253281/git-was-not-found-in-your-path-skipping-source-download maybe you can find a solution there. Good luck!

**Comment by SpencerPlanton** [comment]
I think this may have been user error on my part. I deleted everything and used : 
**_composer require endroid/qr-code_**
and all worked.

However,

on a simple test:

<?php
	require "functions/QRcode/vendor/autoload.php";
	use Endroid\QrCode\QrCode;
	$qrCode = QrCode::create('Life is too short to be generating QR codes');
?>

I get an error: 

**_Fatal error: Uncaught Error: Call to undefined function Endroid\QrCode\Encoding\mb_list_encodings() in E:\wwwroot\wmfltdonline-office\www\functions\QRcode\vendor\endroid\qr-code\src\QrCode.php:16 Stack trace: #0 E:\wwwroot\wmfltdonline-office\www\functions\QRcode\vendor\endroid\qr-code\src\Encoding\Encoding.php(12): [constant expression]() #1 E:\wwwroot\wmfltdonline-office\www\functions\QRcode\vendor\endroid\qr-code\src\QrCode.php(14): Endroid\QrCode\Encoding\Encoding->__construct('UTF-8') #2 E:\wwwroot\wmfltdonline-office\www\functions\QRcode\vendor\endroid\qr-code\src\QrCode.php(28): Endroid\QrCode\QrCode->__construct('this is a test') #3 E:\wwwroot\wmfltdonline-office\www\QR-code-test.php(15): Endroid\QrCode\QrCode::create('this is a test') #4 {main} thrown in E:\wwwroot\wmfltdonline-office\www\functions\QRcode\vendor\endroid\qr-code\src\QrCode.php on line 16_**

Not sure if this is an indication of an installation error or something I have done incorrectly in the environment.

**Comment by endroid** [comment]
Looks like you don't have the php-mbstring extension installed. You should look that up and try to install it. You can check the output of phpinfo() to verify it is installed. If you see the mbstring extension in the phpinfo() output while the problem still persists, please let me know. In the meanwhile I will add an extra `ext-mbstring` requirement to my library. As it depends on that extension you should not be able to install it without. Thank you and good luck again :)

**Comment by SpencerPlanton** [comment]
Thanks for the pointer.

The PHP.ini line:

**_extension=mbstring_**

Was commented out.
So it looks like the requirment needs adding to the composer install.

I now have a working install - and better than that; a working QR demo. 👍

**Comment by endroid** [comment]
Nice! Glad I could help.
