### ISSUE TITLE
[DOC] Write a UPGRADE.md guide from 3.x to 5.x version

### ISSUE THREAD

**Issue by shakaran** [endroid/qr-code-bundle#80]
I am doing a upgrade from 3.6 to 5.0 (main) of this bundle (for support PHP 8+ versions and Symfony 6.x).

I am having a hard time, since I don't see any UPGRADE document of how to do it.

I am checking every change:
https://github.com/endroid/qr-code-bundle/compare/3.x...main

For the moment, I detect that all config options in yaml file are changed from underscore to a cameCase way.

The more difficult deprecatation is change is the use in controllers:

`use Endroid\QrCode\Factory\QrCodeFactoryInterface;`

to

```
use Endroid\QrCode\Builder\Builder;
use Endroid\QrCode\Builder\BuilderRegistryInterface;
```

In __construct():

`QrCodeFactoryInterface $qrCodeFactory`

To 

`private readonly BuilderRegistryInterface $builderRegistry`

And using with:

`$defaultBuilder = $this->builderRegistry->getBuilder('default');`

But, it seems, that the create() is deprecated by a fluent mode interface, so I have something like this now:

```
$qrCode = $defaultBuilder->create($stringToEncode, ['writer' => $format]);

$qrCode->writeFile($this->getFilename($uuid, $format));
```

I understand that I have to use build() at some point, so I am digging right now on this updates.

I will appreciate some guiding or if we can create some kind of document with all the steps needed.

In fact, we can create a custom rector.php rules for make this migration even more easy.

Update with writeFile to saveToFile:

```
            $defaultBuilder = $this->builderRegistry->getBuilder('default');
            $defaultBuilder->data($stringToEncode)->writer($format);

            $result = $defaultBuilder->build();
            $result->saveToFile($this->getFilename($uuid, $format));
```

**Comment by endroid** [comment]
Hi @shakaran you can use the name of your builder when injecting in your controller like described in https://github.com/endroid/qr-code-bundle?tab=readme-ov-file#using-builders. So if you have a builder named 'default' in your YAML you can inject it using `BuilderInterface $defaultBuilder`.

You can find some more extensive examples on how to use the builder and work with result objects here: https://github.com/endroid/qr-code. Good luck!
